Fixes getCurrentlyBuildingJobs()
The escaping caused this exception from Jenkins:
javax.servlet.ServletException: org.dom4j.InvalidXPathException: Invalid XPath expression: /hudson/job[ends-with(color/text(),\"_anime\")] Unexpected '\"_anime\")]'